/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import videoField from "@sklinet/strapi-plugin-video-field/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import comments from "strapi-plugin-comments/strapi-admin";
import heroiconsField from "strapi-plugin-heroicons-field/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import reactIcons from "strapi-plugin-react-icons/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    "video-field": videoField,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    comments: comments,
    "heroicons-field": heroiconsField,
    "multi-select": multiSelect,
    "react-icons": reactIcons,
  },
});
